[bot]
name = MatBot
icon = 
public_play = yes
tournaments = yes
max_games = 2
token = rps_b_-NXEEtU7yftXDikVdBzSq4oaelOK-U1kb9XyEl770Ow
server = wss://api-rps.henhen1227.com/ws
rules_seen = V6:2026-09-03

