[bot]
name = MatBot2
icon = 
public_play = yes
tournaments = yes
max_games = 2
token = rps_b_pvJ-P5OPVPv0RUv1oYiVns5aDsFnBjSTVThQcLfM6YE
server = wss://api-rps.henhen1227.com/ws
rules_seen = V6:2026-09-03